### ISSUE TITLE
Why a link to a malicious website?

### ISSUE THREAD

**Issue by begbaj** [Paguiar735/baileys-quickstart#21]
https://www.virustotal.com/gui/url/b95f9c6b0974fdd299664ad72942839de013c7112a16c63c8bd0a57ae9af0adf/community

Virus total community marks the site as malicious

**Comment by codespearhead** [comment]
https://github.com/codespearhead/baileys-quickstart/blob/0b07289ae93d4746c32bbfcfa8abcb10eb4cc117/src/ServiceLayer.js#L42

That's a [Meta's domain](https://whois.domaintools.com/wa.me) used in [WhatsApp's official documentation](https://faq.whatsapp.com/5913398998672934/?cms_id=5913398998672934&draft=false) for the click to chat functionality:

> WhatsApp's click to chat feature allows you to begin a chat with someone without having their phone number saved in your phone's address book. As long as you know this person’s phone number and they have an active WhatsApp account, you can create a link that will allow you to start a chat with them. By clicking the link, a chat with the person automatically opens. Click to chat works on both your phone and WhatsApp Web.
